### ISSUE TITLE
Is the usage of UNIX socket mandatory ?

### ISSUE THREAD

**Issue by champtar** [jcmoraisjr/haproxy-ingress#104]
Hi @jcmoraisjr 

If I understand correctly, since https://github.com/jcmoraisjr/haproxy-ingress/commit/eb9a8f748bdf08a511a16b2310999be722b0f60e requests are going through haproxy proxy 2 times in every case / configuration
1) do I understand correctly ?
2) can you give an exemple in which case this is required ?

I'm trying to wrap my head around but it might be faster to have the explanation from the author ;)

Thanks
Etienne

**Comment by jcmoraisjr** [comment]
Hi, this is like that since the first version if you use tls, this commit is just using the same approach to plain http requests in order to reuse configuration.

This was built like that because (I think) I cannot use the same frontend with different bind configurations in the same port - namely ca-file and verify none/optional.

There is another reason, simplicity. With unix socket the configuration and specially the template is a mess. Without it the configuration would be even worst.

Anyway I'd happily revise new proposals which simplify the configuration and runs faster, provided that all the current features continue to work.

**Comment by jcmoraisjr** [comment]
This was addressed since v0.8. Closing. Currently a fronting tcp proxy is only used if a ssl-passthrough is used.
