### ISSUE TITLE
TCP services support using annotations

### ISSUE THREAD

**Issue by wenygao** [jcmoraisjr/haproxy-ingress#136]
With tcp-services-configmap, it seems the all traffics to one specific port will route to one fixed backend service. If we need to route to different backend services from same port, how can I do it. For example, there are many backend postgresql services listening on port 5432, the haproxy need to route traffic to postgresql serivces according to host name respectively.

I see the ingress-nginx has already a below solution to meeting the above requirement, is there a equivalent solution in haproxy-ingress?

https://github.com/kubernetes/ingress-nginx/issues/153

**Comment by jcmoraisjr** [comment]
Hi. That proposal was to add an annotation to the ingress resource - which wasn't implemented - and not to support name based routing. Besides that I don't have a clear idea if this is even possible - perhaps using the sni extension from a tls connection - which I also don't know if a psql client support. Afaik using plain tcp does not have support to name based routing. Any help would be welcome here.

**Comment by jodem** [comment]
@jcmoraisjr I agree it's not possible with the hostname, but I would love to see "service port" support. I mean, If we could associated a service port to an ingress to enable a tcp backend it would allow us to configure tcp routing 'per app' instead of having to do it globally with the tcp-service-configmap. It is what they do also in voyager  : https://appscode.com/products/voyager/6.0.0/guides/ingress/tcp/overview/

**Comment by jcmoraisjr** [comment]
Finally implemented a way to use the rich HAProxy Ingress' configuration key list with TCP services. Now TCP services can be configured as an ingress resource. Closing.
