### ISSUE TITLE
Ingress pods automatically goes in crashloopbackoff state after running for a while

### ISSUE THREAD

**Issue by RahulMahale** [jcmoraisjr/haproxy-ingress#141]
Hi, 
We are using haproxy ingress with `canary` tag.
Our haproxy ingress deployment template looks like this.

```

kind: Deployment
metadata:
  labels:
    run: ingress
  name: myapp-staging-ingress
  namespace: myapp-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      run: ingress
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
        run: ingress
    spec:
      containers:
      - args:
        - --default-backend-service=$(POD_NAMESPACE)/myapp-staging-web
        - --default-ssl-certificate=$(POD_NAMESPACE)/tls-certificate
        - --configmap=$(POD_NAMESPACE)/ingress
        - --tcp-services-configmap=$(POD_NAMESPACE)/ingress-tcp-services
        - --ingress-class=haproxy
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/jcmoraisjr/haproxy-ingress:canary
        imagePullPolicy: IfNotPresent
        name: myapp-ingress
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 9000
          name: api
          protocol: TCP
        - containerPort: 1936
          name: stat
          protocol: TCP

```

However after starting the pods, they go in crashloopbackoff state automatically and logs show following error.
```
$kubectl logs -f ingress-255627458-hfpx8
Reload strategy: native
I0423 10:07:51.424577       7 launch.go:141]
Name:       HAProxy
Release:    v0.5-beta.3
Build:      git-2d4dceb
Repository: https://github.com/jcmoraisjr/haproxy-ingress
I0423 10:07:51.424631       7 launch.go:144] Watching for ingress class: haproxy
I0423 10:07:51.424846       7 launch.go:340] Creating API client for https://100.64.0.1:443
F0423 10:07:56.031889       7 launch.go:363] Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration). Reason: Get https://100.64.0.1:443/version: dial tcp 100.64.0.1:443: getsockopt: no route to host
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/ingress-nginx/blob/master/docs/troubleshooting.md

```

Our kubernetes cluster version is 1.7.2. and we dont see this error for any other pods on our cluster.  How can we have stable ingress pods so that we can we have ingress pods running forever and our application routing doesnt breaks.

**Comment by jcmoraisjr** [comment]
Hi, the controller apparently cannot connect to the kubernetes cluster due to a *no route to host* error, this is very specific to your environment.

Whenever you don't use a [kubeconfig](https://github.com/jcmoraisjr/haproxy-ingress#kubeconfig) file, haproxy-ingress will use the in-cluster configuration, ie use the service account token and k8s endpoint provided via envvars. This endpoint is a service IP which kube-proxy configure on every host, perhaps you have a problem on such configuration.

**Comment by RahulMahale** [comment]
Thanks @jcmoraisjr I will try with kubeconfig.

**Comment by RahulMahale** [comment]
@jcmoraisjr  now that pod crashes are fixed we are getting weird issues with application slowness.

We have 40 apps in 40 namespaces with the separate ingress controller. Our app slows down drastically after some time and we have to restart ingress pods to get apps working.

We tried setting up few configuration parameters in the configmap but really not helping out. Also each ingress tracks all the services in all namespaces. We havent used RBAC but I dont think thats the reason it is slowing down our application.

What should be the quick fix ?

**Comment by jcmoraisjr** [comment]
I hope this was properly addressed on your environment. Just for the record v0.10 and newer has metrics and a nice dashboard which help you see what's happening in the cluster, doc [here](https://haproxy-ingress.github.io/docs/examples/metrics/). You might be eg reaching the maxconn limit.

Closing due to the lack of my own feedback. Please find us on slack or any other [community place](https://haproxy-ingress.github.io/community/) if you have any problem.
