### ISSUE TITLE
A/B (Blue/Green based  on service  ips instead of pods)

### ISSUE THREAD

**Issue by lumeche** [jcmoraisjr/haproxy-ingress#158]
While doing some experiments  with  the  blue/green implementation  in haproxy we  discovered  that the  routing  is done  against the  pods ips and  not  the services itself. I understand  that the implementation chosen for  A/B required  to have  a single service. 

In our PoC (Proof of  concept) we defined  three services, one for  Blue, another  for  Green and  another for the  Blue/Green implementation. This since I need to be able to still send traffic  to Blue  exclusively or  Green exclusively.

Now the problems are  the following. 
1. When the A/B is  configured  against the pods, there a  higher changes of having one  pod that receives  more  request that another. We actually proved  with some benchmarks  we did internally where  some pods in  each side got way more  traffic  while other  got almost no request.

2.  Pods  tends  to  vary way more  than service. Imagine  for  example that we implement HPA (Horizontal Pod  Autoscaler) which means  pods will be deleted and created  all the time by k8s. By doing A/B against the Service  this scale up/down will be  transparent  for  haproxy but  by doing  it against the  pods, the  haproxy.cfg file  will need to be regenerated all  the time and risks   are  higher  of  having a  mismatch that will lead us of  loosing some  transactions.

**Comment by jcmoraisjr** [comment]
Hi, regarding using k8s service instead of using pods you can try `ingress.kubernetes.io/service-upstream` annotation as `true`.

Regarding unbalance weight because of the number of pods, this is an already [documented](https://github.com/jcmoraisjr/haproxy-ingress#blue-green) (see "Note that...") issue that I'll try to address in a future version.

The chance of a request choose A or B is the same using services or pods provided that one know how this balancing currently works (the issue talked above). If the configuration is property built and HPA isn't used you should be safe.

**Comment by jcmoraisjr** [comment]
`blue-green-mode` was implemented to fix just this scenario. Doc [here](https://haproxy-ingress.github.io/docs/configuration/keys/#blue-green).
