### ISSUE TITLE
Routing tcp port traffic

### ISSUE THREAD

**Issue by kblooie** [jcmoraisjr/haproxy-ingress#186]
I would like to setup ingress for both http traffic and tcp traffic routed by hostname. I've been able to route https traffic by hostname just fine. However, I'm not sure how to setup the ingress rules so that TCP traffic for the same host name on port (38888) gets routed to the service's 38888 port.

Is this possible? How would I set this up?

In the example below, how do I route traffic from tcp://some.mydomain.com:38888 to some-service:38888?

```apiVersion: v1
kind: Service
metadata:
  name: some-service
  namespace: default
spec:
  ports:
  - name: http-api
    port: 8080
    protocol: TCP
  - name: tcp-server
    port: 38888
    protocol: TCP
  selector:
    app: some-app
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
  name: some-ingress
spec:
  rules:
  - host: some.mydomain.com
    http:
      paths:
      - backend:
          serviceName: some-service
          servicePort: 8080
        path: /
```

**Comment by jcmoraisjr** [comment]
Hi, have a look at the [tcp services command line option](https://github.com/jcmoraisjr/haproxy-ingress#tcp-services-configmap).

**Comment by kblooie** [comment]
Thanks, I saw that documentation, but was a bit confused about it's use. I'm trying to route TCP connections from multiple hosts. Based on the example, it looks like I'd need a unique port number for each host.

By editing the tcp-configmap, do you bypass the need for an ingress definition?

Are you still able to route by host when routing TCP connections that use SSL?

If defining multiple ports in the configmap, do you need to modify the ports available in the HAProxy deployment / daemonset?

**Comment by jcmoraisjr** [comment]
> Based on the example, it looks like I'd need a unique port number for each host.

You'll need a unique port number for each destination service.

> By editing the tcp-configmap, do you bypass the need for an ingress definition?

Yep, tcp-configmap create the proxy without the need to create an ingress object.

> Are you still able to route by host when routing TCP connections that use SSL?

Currently tcp-configmap only support L4 proxy and no hostname information is provided to loadbalance. You'll need to listen different ports for different services. SSL services will work provided that you make the offload on the backend side.

> If defining multiple ports in the configmap, do you need to modify the ports available in the HAProxy deployment / daemonset?

It depends on how you configured the deployment - if you are not using host network, the port should be declared in order to kube-proxy forward incoming connections to the haproxy container.

hth

**Comment by kblooie** [comment]
Thanks for the information!
