### ISSUE TITLE
Why not use haproxy-ingress-controller healthz port as default backend?

### ISSUE THREAD

**Issue by Nefelim4ag** [jcmoraisjr/haproxy-ingress#196]
subj,
AFAIK default backend image is permissible as long, as:
1. It serves a 404 page at /
2. It serves 200 on a /healthz endpoint

So, haproxy-ingress-controller internal healthz port 10254 are fully suitable for that.
And that allow to not use external image for default backend.

Did i miss something?

Thanks!

**Comment by Nefelim4ag** [comment]
Example what i mean:
https://github.com/jcmoraisjr/haproxy-ingress/pull/197

**Comment by jcmoraisjr** [comment]
Hi, in fact a default backend implements whatever one wants to be shown by the ingress controller when a domain or a page isn't found. Take eg a non existing subdomain under `*.herokuapp.com` - this is an example of a default backend. The current default image under the docs should be considered as a placeholder - with a small default image which shows a boring 404.

**Comment by Nefelim4ag** [comment]
@jcmoraisjr, i.e. no some magic sense?
i.e. Ingress controller refuse to work without default backend, so i thought that some hidden sense.

**Comment by jcmoraisjr** [comment]
There are some mandatory command line arguments and the default backend is currently one of them. Are you proposing to change it to optional?

**Comment by Nefelim4ag** [comment]
@jcmoraisjr, as controller are cloned from nginx-controller, i don't think that worth it.

But yes, default backend which only server 404 looks like overengineering - that's easy to use some page for haproxy/nginx to server 404 instead of deploy another tiny app.

And if someone want replace 404 page with own not by mounting file in container (from ConfigMap as ex), then they free to configure some external service.

Thanks.

**Comment by jcmoraisjr** [comment]
This controller used the core and so called reusable part of the so called k8s/ingress as a dependency, which would make changes to that code a bit harder. Reusable ingress doesn't exist anymore so haproxy ingress now evolve its own core which make such changes as simple as any other.

I like the idea to start simple but I also like the idea to start with placeholders that you just need to fill in order to make stuff happen. Take the configmap as an example - the deployment doc says the user should kubectl create configmap before deploy the ingress deploy/daemonset. This should sound an overkill but if he need - and he will - add some customization, the configmap is there.

I have no objection (actually) to change default backend to an optional command line argument but I'd not change everything and every doc to simply remove this option. Instead I'd doc everywhere this is an optional step.

Regarding implementation I'd use a 404.html as an errorfile of a new listener created only if a default backend wasn't provided. Healthz doesn't sound a good idea because /healthz should also return 404.

**Comment by Nefelim4ag** [comment]
```
~ wget -O - http://127.0.0.1:10254/healthz 2>&1 | grep HTTP
HTTP request sent, awaiting response... 200 OK
```

Anyway thanks.
