### ISSUE TITLE
Better control of weights in blue/green deployments

### ISSUE THREAD

**Issue by daniloegea** [jcmoraisjr/haproxy-ingress#199]
Hello,

Maybe it's better using a haproxy configuration like [this](https://gist.github.com/daniloegea/619156903eeb85f09bfc462b50a3bafe).

You can group blue and green pods in separated backends and distribute the load to them. I think it solves the weight problem described in the docs.

Thanks.

**Comment by jcmoraisjr** [comment]
There is already a rework planned on blue/green in order to solve issues like the pod-based weight and the need to declare two new k8s services. Regarding pod-based weight my initial idea was to recalculate all the weights based on the number of pods on each side. Another idea is to separate into two backends just like your proposal, but this would use even more unix sockets which I'd like to avoid. Ainda assim obrigado pela análise e pela dica ;)

**Comment by daniloegea** [comment]
Entendi, obrigado ;)
