### ISSUE TITLE
Implement health check

### ISSUE THREAD

**Issue by jcmoraisjr** [jcmoraisjr/haproxy-ingress#21]
Implement an URL used for health check

**Comment by woopstar** [comment]
Wouldn't it be as simple, as to implement this in the haproxy.cfg

```
# Use /healthz to report haproxy's status
frontend healthz
    mode http
    monitor-uri /healthz
```

According to the documentation at http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4-monitor-uri:

`is the exact URI which we want to intercept to return HAProxy's health status instead of forwarding the request.`

**Comment by jcmoraisjr** [comment]
Sure, haproxy.cfg is probably the way to go. Implement here means configure, perhaps listening another port and taking care with port conflict on deployments where hostNetwork is true, and also document and update the deployment instructions.

**Comment by woopstar** [comment]
Well, you cannot use the health check if you run with hostNetwork to true or am I wrong?

**Comment by jcmoraisjr** [comment]
> Well, you cannot use the health check if you run with hostNetwork to true or am I wrong?

It works, the difference is that the IP of the pod - which is the default value of `probe/httpGet/host` - is the IP of the host instead of an IP of the overlay network.

**Comment by jcmoraisjr** [comment]
Implemented on 9260339 .

@westse FYI `accept-proxy` was added on stats page. The HAProxy's health check URI defaults to `:10253/healthz`.

**Comment by westse** [comment]
@jcmoraisjr, I just realized `/healthz` works for health checking, but the stats page still needs `accept-proxy` to be omitted for internal metrics gathering. For example, I plan to use [haproxy_exporter](https://github.com/prometheus/haproxy_exporter) in the same pod as haproxy-ingress in order to get metrics into Prometheus.

Options I see:
1. Remove `accept-proxy` from stats page
1. In addition to `add-proxy-protocol`, add another property (e.g. `use-proxy-protoco-for-stats`) for independently setting `accept-proxy` on the stats page

Which do you prefer, or do you see another option? I can produce a PR if you would like. Also, do you want an issue created?

Thanks

**Comment by jcmoraisjr** [comment]
@westse thanks for pointing this out, I'll also use HAProxy with Prometheus and will probably have the same issue.

A PR would be handy. Use `stats-proxy-protocol` property.
