### ISSUE TITLE
x-forwarded-for "ifmissing" by default

### ISSUE THREAD

**Issue by theonlydoo** [jcmoraisjr/haproxy-ingress#244]
Hi,

We noticed that x-forwarded-for is replaced **by default**, which is quite disturbing.

Could `ifmissing` be the default behaviour? That way it wont interfere with previously existing headers by default, and fill the void if there is any.

Cheers.

**Comment by jcmoraisjr** [comment]
Hi, the default configuration is meant to be used on untrusted networks, this is by design, and apps behind such reverse proxy will trust the x-forwarded-for has the real src address. Because of that I cannot change the default behavior. If you have another lb in front of haproxy you can choose between ifmissing or proxy-protocol which should also solve the problem.

**Comment by theonlydoo** [comment]
forgot to close the issue, thanks for the reply :)
