### ISSUE TITLE
How can i configure a path for the statistics page

### ISSUE THREAD

**Issue by LordOfRhun** [jcmoraisjr/haproxy-ingress#313]
Hi, I am trying to configure a path for the statistics page and I haven't found information. I am asking this because i have no idea on how to access it normally.

i would like to be able to access it like this : 'ip':'port'/stats.

**Comment by jcmoraisjr** [comment]
Hi, the status page uri is hardcoded [here](https://github.com/jcmoraisjr/haproxy-ingress/blob/v0.7-beta.8/rootfs/etc/haproxy/template/haproxy.tmpl#L746) so you need to overwrite the whole template in order to change it. You can however change the port number using a configmap option but cannot reuse the same ports for ordinary http/https requests.
