### ISSUE TITLE
BufferSize support in template

### ISSUE THREAD

**Issue by devlounge** [jcmoraisjr/haproxy-ingress#325]
Hi,

I can see in the 0.7 release some support for configuring the buffer size:

Configuration.BufferSize in pkg/common/ingress/annotations/proxy/main.go
as well as
proxyCfg.BufferSize  in pkg/common/ingress/controller/controller.go

But no new line for setting tune.bufsize in the template.

Anytime soon?

**Comment by jcmoraisjr** [comment]
Hi, this controller started as a HAProxy implementation of a generic "ingress controller" - which doesn't exist anymore and now is called ingress-nginx. Because of that there are several annotations - some very close to nginx and others that simply wasn't implemented yet there are flying in the code.

Regarding `tune.bufsize` you can configure using `config-global` configmap option.
