### ISSUE TITLE
No option to ignore Ingress without set class

### ISSUE THREAD

**Issue by the-nicolas** [jcmoraisjr/haproxy-ingress#326]
Hi

I was searching for a configuration option to disable ingress for ingress resources where class is not set.

nginx-ingress has that option for that: [-use-ingress-class-only](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/cli-arguments.md)

After reviewing the code HAProxy is just checking for "class.valid" and valid is also true, if class is not present:

https://github.com/jcmoraisjr/haproxy-ingress/blob/e44de22a8472912b680b5f0e134c08e6467361d0/pkg/common/ingress/controller/controller.go#L302

Would be perfect to also have an option to configure that. Or even better something like:
ingress-class = "!haproxy"

In my opinion some decorator to "force strict checking" is even simpler than having XXX options for everything.

**Comment by alanpearce** [comment]
I noticed that ingresses without a class are actually ignored if I configure haproxy-ingress with an ingress class other than `haproxy`. I would also like an explicit option to control this as we will need to match empty ingress classes whilst migrating.

**Comment by jcmoraisjr** [comment]
Hi, a similar feature was merged on #527 and it's available since v0.10-snapshot.4, doc [here](https://haproxy-ingress.github.io/docs/configuration/command-line/#ignore-ingress-without-class). It uses an inverted logic (ignore instead of use) but should work as expected.

This could also be improved using a list of classes, enforcement and exception (named classes to be ignored) but, since this annotation is [deprecated on k8s 1.18](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#extending-ingress-with-and-replacing-a-deprecated-annotation-with-ingressclass), any improvement should be directed to the new IngressClass resource. So closing this fr and sorry about taking so long to comment on this.
