### ISSUE TITLE
Cannot authenticate on docker registry

### ISSUE THREAD

**Issue by tiagomiguelsousa** [jcmoraisjr/haproxy-ingress#345]
hello to all.
I've configured a k8s cluster with HAProxy (with SSL termination and certificates well configured) as Ingress. One of my backends is Nexus acting as docker registry.
To access the docker registry i've open a TCP port (tcp-services) in HAProxy (8083: "default/nexus-svc:8083").
My problem is that i cannot login to the registry without adding the certificates on client's side or setting insecure-registry on client's docker daemon. 
My question is: what annotation should i use on HAProxy so that i can login on docker registry without changing the client's daemon or adding any certificates on client's side?
Thanks a lot.

Tiago

**Comment by jcmoraisjr** [comment]
Hi, haproxy ingress is configured in front of your registry, right? Do you mean some annotation or another configuration on the controller so that you don't need to add neither ca-cert/insecure-config nor authentication? If so haproxy ingress cannot help you since it acts as a pure tcp proxy. This is your options:

1. you'll need to authenticate or leave a `~/.docker/config.json`, or remove authentication from your server somehow
2. you'll need to use a public and valid certificate authority in order to docker client doesn't complain with your server certificate.
