### ISSUE TITLE
[Question] Is regex in HTTPIngressPath supported?

### ISSUE THREAD

**Issue by mvpmvh** [jcmoraisjr/haproxy-ingress#350]
[this issue](https://github.com/jcmoraisjr/haproxy-ingress/issues/207) is closed, but I can't tell if anything ever came of it.
Is it possible today to use regex to route to backends?

**Comment by jcmoraisjr** [comment]
Hi, this sounds a fair addition to v0.8. I'll take care of this.

**Comment by sergiimk** [comment]
We have also encountered this limitation as we are transitioning to `haproxy-ingress` from `ingress-nginx` and needed feature parity with its [regex matching](https://kubernetes.github.io/ingress-nginx/user-guide/ingress-path-matching/#regular-expression-support).

We worked around this by introducing the `ingress.kubernetes.io/path-type: regex` annotation and having controller use [HTTPFrontsMap.RegexFile](https://github.com/jcmoraisjr/haproxy-ingress/blob/master/rootfs/etc/haproxy/template/haproxy.tmpl#L789) map file  instead of the `MatchFile` for paths that are part of such annotated ingress.

Our implementation is definitely on a "quick and dirty" side (though happy to share if needed), so it would be great to see this feature properly supported. Regex rules are very useful for bulkhead-style QoS and slicing up old monoliths into smaller services.

**Comment by jcmoraisjr** [comment]
Hey, thank you for choosing haproxy ingress and sorry about this missing feature. Please share your code creating a new PR, I'll have a look before cutting v0.10 to beta.

**Comment by sergiimk** [comment]
I've tried upgrading to latest version today that includes #641. I followed the docs and used:
```yaml
path: ^/v[0-9]+/(foo|bar)/
```
But this gets rejected by k8s:
```
The Ingress "foo" is invalid: spec.rules[0].http.paths[0].path: Invalid value: "^/v[0-9]+/(foo|bar)/": must be an absolute path
```
Which is related to kubernetes/kubernetes#68413

When using:
```yaml
path: /v[0-9]+/(foo|bar)/
```
I of course get an incorrect regex in `/etc/haproxy/maps/_front_https_host__regex.map`:
```
^foo\.example\.net/.*/v[0-9]+/(foo|bar)/ ...
```
which will not match a path like `/v1/foo/x` as it expects an extra slash...

@jcmoraisjr did you encounter this problem during #641? Perhaps there's a workaround to bypass kube's (quite useless) validation that I'm missing?

**Comment by jcmoraisjr** [comment]
Hi, in fact ingress validation would make the current implementation unusable since one couldn't match the start of the path. I've just pushed #651 which adds an implicit starting match, making regex behaves pretty much like the `begin` match option. Please have a look at the implementation and report back any issue or any suggestion. Thanks for quickly report this.

**Comment by sergiimk** [comment]
Can confirm that #651 fixes the issue for us :+1: 
Thanks for such a quick turnaround.

**Comment by jcmoraisjr** [comment]
Tagged `v0.11-snapshot.3` with this fix. Thanks also for the fast feedback! Closing, let me know if you have any problem.
