### ISSUE TITLE
improved oauth support

### ISSUE THREAD

**Issue by billimek** [jcmoraisjr/haproxy-ingress#413]
Currently the [oauth documentation](https://github.com/jcmoraisjr/haproxy-ingress#oauth) and [example](https://github.com/jcmoraisjr/haproxy-ingress/tree/master/examples/auth/oauth) suggest that it is only possible to configure an ingress to use oauth by configuring a specific ingress backend for the `/oauth` (or configured `oauth-uri-prefix` path).

This limits the ability to leverage oauth with purely annotations as is [currently possible with something like the nginx ingress controller](https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/auth/oauth-external-auth).

It would be good if we could do oauth configuration purely with annotations when using the haproxy ingress controller.

**Comment by jcmoraisjr** [comment]
Hi, do you mean authenticate requests only on paths whose ingress objects
has the oauth annotation? This is the current behavior since v0.8, pleaae
have a look and let me know if you'd expect something different.

~jm


Em qui, 17 de out de 2019 22:57, Jeff Billimek <notifications@github.com>
escreveu:

**Comment by billimek** [comment]
Hi @jcmoraisjr, I think I may mean something different or perhaps I don't understand how to use it properly now.  What I mean is this:

For a given ingress object, to use haproxy and oauth together, the ingress object must look something like this snippet:

```yaml
  annotations:
    ingress.kubernetes.io/oauth: oauth2_proxy
  name: some-app
spec:
  rules:
  - host: some-host
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /oauth2
      - backend:
          serviceName: some-app-service
          servicePort: 8080
        path: /
```

The part above about about the `oauth2-proxy` and `/oauth` path are net-new required parts of the ingress itself beyond the application backend. From what I understand, haproxy expects there to be a `/oauth2` path under the application host URL.

In the nginx ingress world, we reference an oauth2 as simply annotations to the ingress object, like so using the above snippet:

```yaml
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "https://some-host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://some-host/oauth2/start?rd=$escaped_request_uri"
  name: some-app
spec:
  rules:
  - host: some-host
    http:
      paths:
      - backend:
          serviceName: some-app-service
          servicePort: 8080
        path: /
```

The key difference is that the reference and configuration of the oauth are only annotations.  This is very useful because, in the case of things like helm charts, adding additional annotations to an ingress is usually supported and baked-in.  Adding new backends is not.

**Comment by jcmoraisjr** [comment]
I see, the current implementation expects an oauth service per hostname, because of that only an URI is used, which defaults to `/oauth2`. The `auth-url` below is only allowing you to use another hostname. What if an `oauth-url` annotation was added which would expect `https://some-host/oauth2`?

**Comment by billimek** [comment]
Yeah I think an `oauth-url` annotation may work!

Do you know how the 'callback' URL flow is handled today with haproxy & oauth-proxy?  For some reason to be successful with the nginx oauth-proxy flow, I needed to define this additional annotation as well.

**Comment by jcmoraisjr** [comment]
> Do you know how the 'callback' URL flow is handled today with haproxy & oauth-proxy?

Yep, haproxy-ingress handles /start, /auth, /callback and so on out of the box.

**Comment by travisghansen** [comment]
I would like to see an implementation that follows the pattern/spec of envoy or traefik (or a lesser degree even nginx) integrated into the controller.

- https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ext_authz_filter
- https://docs.traefik.io/middlewares/forwardauth/
- https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/

My ultimate goal is to make it integrate with the ingress via a single annotation which specifies any arbitrary endpoint (internal or external to cluster) to utilize with a little auth server I wrote (which integrates with oauth/ldap/jwt/etc with simple/powerful assertions):

- https://github.com/travisghansen/external-auth-server

If the request should be a separate issue let me know and I'll open up something new altogether.

Thanks!

**Comment by travisghansen** [comment]
In essence a generic version of this: https://github.com/jcmoraisjr/haproxy-ingress/issues/200
But instead of pointing to a haproxy backend it can point to any arbitrary endpoint. I would guess a slightly modified version of https://github.com/TimWolla/haproxy-auth-request would be required to make it work.

**Comment by travisghansen** [comment]
Still valid.

**Comment by jcmoraisjr** [comment]
Finally implemented a proper external authentication in `v0.13.0-snapshot.1`. Closing.

@travisghansen it'd me awesome to have an example doc of external authentication using your component =)

**Comment by travisghansen** [comment]
Can you point me to the documentation of how it was implemented and I can take a took!

**Comment by jcmoraisjr** [comment]
Thank you so much for your time! The relevant doc is [here](https://haproxy-ingress.github.io/v0.13/docs/configuration/keys/#auth-external) and reach us on slack if you need anything.

**Comment by travisghansen** [comment]
Thanks for sending the link! I’ll try to set it up but it appears to unfortunately be generally based on the nginx style vs the envoy/traefik style. That will make it less flexible and more challenging but I’ll see if I can make it work.

The key difference is, in the case of a non 2xx response code the envoy/traefik model returns the response from the auth service unaltered rather than forcefully sending a 403. This allows for a much more dynamic process vs the static sign-in url. For example some (oauth) providers require a `nonce`...or maybe I want to send a 401 vs a 403 and/or include a `www-authenticate` header with a specific bearer realm etc.

It’s great to have this implemented! It would just be better to support the other style...maybe as a distinct feature?

**Comment by jcmoraisjr** [comment]
Thanks for the feedback! Because of that we have snapshot versions =) I'll have a look on the envoy/traefik docs out there and improve this implementation before we move to beta. I'll notify you in this same issue.

**Comment by travisghansen** [comment]
That is fantastic to hear! I’ll hold tight with testing.

**Comment by travisghansen** [comment]
I should note, the envoy implementation is different than the traefik implementation...but in both cases the response is returned unaltered if non 2xx.

**Comment by jcmoraisjr** [comment]
Thanks for the valuable feedback, external authentication options isn't something I'm familiar with and its a bit hard to define a decent user interface with all the current limitations.

Your proposal is pretty close to what I was thinking about a good spec, there were two situations counting against it: backward compatibility and auth-requests. The first one doesn't make sense because it's just a snapshot. There is also oauth but I can make it compatible with the new internals so it isn't a problem at all.

auth-requests on the other hand is the main limiter here: it doesn't give me an option to list all the headers received by the auth service and this limitation guided all the current spec. I however decided that this script need to be maintained by the haproxy ingress project, the current and probable future work arounds in the code is even harder to maintain. I'll try to follow your first suggestion, this will take a few more days to tag a new snapshot, but with the benefit to have a better interface to the user, and also a better code base to maintain in the long run.

Thanks for your time spent on this - past and I hope future time as well.

**Comment by travisghansen** [comment]
I’ve not much experience with `oauth2-proxy` but I don’t think it’s primary use-case is this pattern so I’m not sure how worried I’d be with that one.

Speaking generally the approach I mentioned should work quite nicely with several others auth servers that are built to handle the pattern including various that support oauth/oidc (my project inclusive, but also I believe authelia etc). I actually created my project initially due to perceived limitations in `oauth2-proxy` including its inability to work with the proposed pattern, the need to deploy it over and over to have various configurations, etc.

**Comment by jcmoraisjr** [comment]
Here is a new attempt, now almost rewriting auth-request.lua on behalf of a clear configuration option to the user.

https://github.com/jcmoraisjr/haproxy-ingress/blob/fde407fdeb9d12e93c471b20e0ce050ff1dff491/docs/content/en/docs/configuration/keys.md#auth-external

**Comment by travisghansen** [comment]
I’ll read it over!

**Comment by travisghansen** [comment]
This looks really great! A couple followup questions before I move on to actually setting up an env and testing it out:

- what is the current behavior with `x-forwarded-*` headers being passed to auth-url? it’s effectively required in the case of my auth server to have some way of knowing the full uri of the original request with preferably also the verb/method used
- are query params valid in the auth-url?
- The `svc` feature for the auth-url seems pretty cool. Is it possible to allow that cross namespace?

A couple random thoughts to consider:

- some may like an ability to have the auth request verb/method match the original request verb/method rather than hard-coded....doesn’t matter in my case (assuming I can get the verb via a header)
- it may be beneficial to allow for operators to inject specific headers with specific values to the auth-url (ie: auth to auth-url type stuff or other pieces of metadata not to be sent/trusted from the client)

**Comment by jcmoraisjr** [comment]
> This looks really great!

🎉  this feature was a piece of a hard work =) Thanks for the help making it even better.

> what is the current behavior with `x-forwarded-*` headers being passed to auth-url? it’s effectively required in the case of my auth server to have some way of knowing the full uri of the original request with preferably also the verb/method used

It should be provided as a client header, you can filter in/out if needed. Currently we don't have `X-Forwarded-Method`, need to improve the X-Forwarded headers family. Anyway you can add it manually with `headers` config key, doc [here](https://haproxy-ingress.github.io/docs/configuration/keys/#headers). This is a log-formatted field so you can use eg `%[src]` as the field value.

> are query params valid in the auth-url?

Yep, just concatenate `?query` after the path.

> The `svc` feature for the auth-url seems pretty cool. Is it possible to allow that cross namespace?

Currently no but it's a fair improvement. Probably enabled via a global option for security.

> some may like an ability to have the auth request verb/method match the original request verb/method rather than hard-coded....doesn’t matter in my case (assuming I can get the verb via a header)

Good point, it's simple to implement, I'll take care of it.

> it may be beneficial to allow for operators to inject specific headers with specific values to the auth-url (ie: auth to auth-url type stuff or other pieces of metadata not to be sent/trusted from the client)

This can be done with the `headers` config key.

---

Note that this improvement is on an opened pull request which I still need revise and merge. There are some other pending merges and after that a tag will be added with the functionality. I'll notify here as soon as this happens, hopefully in the next 2 or 3 days. Probably the aforementioned features won't be included right now but planning to add in the next tag.

**Comment by travisghansen** [comment]
OK awesome! So the `headers` tag would push values down to both the auth service and the service?

Got a sample `values.yaml` I can use to deploy with the supporting version etc? I'll give it a go and see how things play out!

**Comment by jcmoraisjr** [comment]
Yup, header manipulation and auth-request action runs via http-request keyword, which are executed in the order of the declaration, and the header assignment runs first. You can also remove a header after being read by auth-request and the external service using a config snippet, which is configured after the the response of the external service and runs after the service receive it.

I'll paste a sample here as soon as the version is tagged and published.

**Comment by jcmoraisjr** [comment]
A new v0.13 snapshot was tagged and [auth-external doc is now published](https://haproxy-ingress.github.io/v0.13/docs/configuration/keys/#auth-external). Just run helm with `--version 0.13.0-snapshot.2 --devel` to use the latest version, doesn't need any special configuration in the `values.yaml` except what you already use to properly expose the controller (eg hostNetwork, service type, etc). [Getting started](https://haproxy-ingress.github.io/v0.13/docs/getting-started/) has the details. I'm already taking care of cross namespace, propagate http method and other improvements to the next tag.

**Comment by travisghansen** [comment]
Just getting around to trying this out. Not directly related but would help my testing...how do I configure the controller to update the IP on the ingress objects? Does this controller support that?

**Comment by jcmoraisjr** [comment]
Hi great news!

> how do I configure the controller to update the IP on the ingress objects?

If you mean the dns in the http protocol, it doesn't. You'd need to force a reconciliation, eg editing any attribute in the configmap (full sync) or in the ingress with the dns (partial sync). svc proto should update as soon as the pod ip changes.

> the x-forwarded-uri value. Is it possible to make the values conditional?

Maybe you prefer to use [`%[pathq]`](http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#7.3.6-pathq) instead, available since haproxy 2.2.

**Comment by travisghansen** [comment]
I was referring to the publish service functionality...but I got it going. Let me try pathq to see how that works out.

**Comment by travisghansen** [comment]
Yes, `pathq` is a perfect fit. Any particular tests you'd like me to run through at this point? I'm testing with my most complex plugin (`oidc`) so if that works pretty much any of the others will work.

**Comment by jcmoraisjr** [comment]
> Any particular tests you'd like me to run through at this point?

Maybe check if failure scenarios like forcing a timeout, handshake errors etc would always deny the user to reach the backend servers. Other than that it seems your current tests have already a good coverage.

**Comment by travisghansen** [comment]
OK, setting https for an http only service results in the browser receiving a `500` (presumably from the lua code, not from the auth backend). I think you're all set with this one! Now I can revisit using haproxy as my general ingress controller!

Final config for me is:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-url: http://eas-external-auth-server.external-auth-server/verify?config_token=...
    ingress.kubernetes.io/headers: |
      x-forwarded-host: %[req.hdr(Host)]
      x-forwarded-uri: %[pathq]
      x-forwarded-method: %[method]
```

**Comment by jcmoraisjr** [comment]
`v0.13.0-snapshot.3` also implements the ability to use svc from other namespaces and http method can also be copied from the client request; [doc](https://haproxy-ingress.github.io/v0.13/docs/configuration/keys/#auth-external) updated. Closing, and let me know if you have any other issue.
