### ISSUE TITLE
mTLS requirement is ignored if the secret is missing causing the Ingress endpoint to be available on the public internet

### ISSUE THREAD

**Issue by primeroz** [jcmoraisjr/haproxy-ingress#418]
## Overview

When creating an ingress with mTLS enabled through annotation `ingress.kubernetes.io/auth-tls-secret: ingress-controller/client-auth` if the secret is missing or missing the `ca.crt` key then the mTLS requirement will be ignored and a _normal_ , publicly available, ingress is created.

This situation can happen for a lot of reasons:
1. simple mistake / bad update of secret resource 
1. using a dynamic provisioner for creating the secret , like _cert-manager_ 

the `cert-manager` one is my case , using the Vault Issuer. 
When using cert-manager to create a Certificate there will always be a window of time when the secret is not available yet. 
This is , in my case, **exacerbated**  by the fact that we use [flux gitops](https://github.com/fluxcd/flux) to deploy all resources in the cluster. 
When a new cluster is brought up we apply all resources at once and then we let kubernetes reconcile all the requested resources ... this can take a while and there will be a time, which can be relatively long, where the ingress controller is running but cert-manager is not yet ... making my protected ingress available to everyone on the internet

I think this is a big Security Issue

I tested this behavior on `0.7.3` (which is what i run) and `0.8-beta.3` 

## What i would like 

I think that for Ingresses that are **supposed to be secure** the failure mode should be **hard** rather than the soft one we have now.

I am not really concerned into what kind of hard failure we get , it could be any of :
1. No Ingress rule at all is created on haproxy , request will go to default backend
1. Dedicated error page backend similar to the `backend errorXXX` ones with a custom message
1. Use a fake certificate + ca so that no one can authenticate 

## To reproduce 

1. Start a cluster using your favourite tool ( kind , minikube, gke, ... ) 
1. Create haproxy ingress controller
1. Create a mtls protected ingress with no secret
1. Access the Hostname 

## What have i tried ?

I have been going to through the code with the hope to provide an MR but the code is rather complicated for me and still have not managed to understand the whole flow to understand where such an Hard failure should be inserted.

**Comment by jcmoraisjr** [comment]
Hi, I understood the scenario and I also agree with your arguments. The idea behind the current behaviour is that a config error is reported in the log and such config isn't applied. This seems valid for some configs but it doesn't for security one.

I'll revisit configs like whitelists, basic and TLS authentications and so on in order to fail always in the case of a misconfiguration. In your scenario you'd receive a HTTP 495 status code until all the config is in place. Thanks for sharing this.

**Comment by primeroz** [comment]
That sounds perfect thanks. I hope we will get a 0.7 release with the patch as well as the new 0.8 since i am not ready to upgrade

**Comment by jcmoraisjr** [comment]
Hi, this will be a v0.9 implementation that will probably be merged to v0.8 due to security reasons. v0.7 uses an old and just deprecated controller: the implementation would need to be made twice and with much more effort. I'd instead invite you to test v0.8 on a staging environment or a production host outside your dns or fronting lb - we're happily using it in production since beta.2.

**Comment by primeroz** [comment]
I started looking into 0.8 , it make sense to go for it anyway.

https://github.com/jcmoraisjr/haproxy-ingress/issues/429

**Comment by jcmoraisjr** [comment]
HI, a new config key `auth-tls-strict` was added which implements this behaviour. Note that it's `false` by default due to backward compatibility but should be changed to `true` in v0.10 or v0.11. You can change globally changing its value in the configmap, or per ingress object using annotation. This was added in v0.8.1, v0.9-beta.2 and v0.10-snapshot.3 which were released yesterday. Closing and please update this same issue if you have any problem.
