### ISSUE TITLE
WAF being used in ingress without annotation

### ISSUE THREAD

**Issue by GMartinez-Sisti** [jcmoraisjr/haproxy-ingress#421]
I was testing modsecurity with the documentation provided, and noticed that as soon as I deployed it it started blocking traffice from other ingresses without the annotation.

Looking at the haproxy configuration, I would assume that blocking would only occur when the annotation is set, but that is not the case. I'm using v0.7.2.

Is this known?

Thanks

**Comment by jcmoraisjr** [comment]
Hi, v0.7 configures the waf filter in the frontend so every single request will trigger the filter. We couldn't bypass this in haproxy 1.8. So you'll see requests to every single deploy in the waf logs. However deploys without the annotation shouldn't be blocked despite of the waf response.

Please let me know if:

* you're being blocked on deploys/svc/ingress without annotation or you're just seeing blockings on the waf logs
* v0.8 works on your deployment - since v0.8 the waf filter is in the backend so only annotated ing/svc/deploys will call the waf backend

**Comment by GMartinez-Sisti** [comment]
Hi, thanks you for your fast reply!

I can confirm that the requests are not blocked, only logged by the waf.

Regarding v0.8-beta.3, would you say it's production ready?

Obrigado!

**Comment by jcmoraisjr** [comment]
Hi, I consider v0.8 in a better state if compared with v0.7 thanks to its new design. There are some known minor issues in place which impact some very specific use cases. I'm releasing beta.4 today which should fix most of them. We are using in production since beta.2.

A disposição.

**Comment by GMartinez-Sisti** [comment]
I can confirm this is fixed with beta.4.

Thanks @jcmoraisjr !
