### ISSUE TITLE
Recommended Grafana dashboard?

### ISSUE THREAD

**Issue by vitobotta** [jcmoraisjr/haproxy-ingress#458]
Hi! I am looking for a nice dashboard that would show req/sec and other useful metrics. Does it exist? I haven't found a good one on Grafana.com. Thanks!

**Comment by jcmoraisjr** [comment]
HI, here is the one we use in production. This is a self-made dashboard since the available ones doesn't fit our needs. Give some feedback so we can improve it and upload to grafana.com.

[haproxy-ingress.json.gz](https://github.com/jcmoraisjr/haproxy-ingress/files/3887912/haproxy-ingress.json.gz)

**Comment by vitobotta** [comment]
Hi @jcmoraisjr! I am trying it but it doesn't show any data? The instance and backend dropdowns have "All" but no other options. Do I need to do something for Prometheus to collect that data? Thanks!

**Comment by jcmoraisjr** [comment]
Hi, the dropdown are grafana variables filled with label_values() and default metrics from [prometheus' haproxy-exporter](https://github.com/prometheus/haproxy_exporter).

Regarding datapoints we're using a mix of v0.8 and v0.9 and some queries might be changed from v0.7/older.

**Comment by vitobotta** [comment]
Not sure I am following. I installed Prometheus/Grafana with Helm (actually with Rancher but it's basically the same thing). With other Grafana dashboard I tried from Grafana.com I do see some data, so that Prometheus instance is scraping some data from haproxy I think. Do I need to install this haproxy-exporter? If yes how? Not sure from reading that page...

**Comment by jcmoraisjr** [comment]
Hi, I'm guessing you changed `controller.metrics.enabled` to `true`? So you should have haproxy-exporter running.

I've just reimported this dashboard on another grafana instance, which points to another prometheus, which is scraping a cluster with v0.8 and v0.9 deployments. Worked like a charm. I'd suggest you to debug your prometheus deployment with some simple queries from haproxy exporter, eg `sum(rate(haproxy_frontend_connections_total[5m]))` and `sum(rate(haproxy_frontend_connections_total[5m])) by (instance)` in order to understand what's missing.

I'm not using helm myself so I cannot say about v0.8 compatibility, but if you are running on a staging environment and an upgrade is an option, update `controller.image.tag` to `v0.8-beta.5` and give v0.8 a chance.

**Comment by cu12** [comment]
A bit better looking version that uses pod names instead of their IP address.

[haproxy-dashboard.json.zip](https://github.com/jcmoraisjr/haproxy-ingress/files/3916737/haproxy-dashboard.json.zip)

**Comment by vitobotta** [comment]
Hi @jcmoraisjr yes `controller.metrics.enabled` is set to true. I see  a `prometheus-exporter` container. I tried those queries in Prometheus and there's nothing related to haproxy. haproxy is also missing in the list of the targets. What can I do to have Prometheus scrape the metrics exposed by the exporter container?

@cu12 Hi, I am trying with that dashboard now but I still have the problem of no data available.

**Comment by vitobotta** [comment]
I forgot to mention that I have updated to 0.8.

**Comment by cu12** [comment]
@vitobotta do you see the metrics in Prometheus? If yes then check your datasource in Grafana.

**Comment by jcmoraisjr** [comment]
Hi, now there is an *almost* oficial Grafana dashboard. Link and usage are described [here](http://haproxy-ingress.github.io/docs/examples/metrics/). Need at least v0.10. Closing.
