### ISSUE TITLE
Possible to name backends by pod name

### ISSUE THREAD

**Issue by cjroebuck** [jcmoraisjr/haproxy-ingress#469]
Instead of srv001, srv002... etc it would be good to have the option to name the backends the same as the pod hostnames. Would it be possible? It would make the haproxy logs more useful figuring out which pod produced which log quicker.

**Comment by jcmoraisjr** [comment]
Hi, servers has such boring name because of dynamic update - the name of the server cannot be changed and would make dynamic updates unworkable. A new config key can be added to choose the server name: sequence, pod name and pod IP are some options but only sequence would allow to enable dynamic update.

**Comment by jcmoraisjr** [comment]
Hi, added in `v0.10-snapshot.3`, `v0.9-beta.2` and `v0.8.1`, use the config key `backend-server-naming` as global or per ingress object as annotation. Docs [here](https://haproxy-ingress.github.io/docs/configuration/keys/#backend-server-naming). Closing. Please update this same issue if you have any problem.
