### ISSUE TITLE
Annotation enable-cors disabled whitelist-source-range

### ISSUE THREAD

**Issue by xFragger** [jcmoraisjr/haproxy-ingress#473]
The whitelist-source-range annotation alone works perfectly, but at the moment i add enable-cors, i can't find the whitelisted IPs/Ranges in the generated haproxy.cfg

I guess thats just a small error in the template, but my haproxy experience is to small, to find this and change this. Out workaround is, that our service will send the cors headers, but thats not like i should work, i guess

```  
annotations:
    ingress.kubernetes.io/whitelist-source-range: "192.168.70.0/24,192.168.150.0/24"
    ingress.kubernetes.io/enable-cors: true
```

**Comment by jcmoraisjr** [comment]
Hi, couldn't reproduce this. What version are you using? Do you mean whitelist is removed or perhaps cors that isn't enabled? Note that the annotation is `cors-enable` instead of `enable-cors`. Please paste the generated backend config - the one between `backend <namespace>_<svc-name>_<port>` and the next one, just change any sensitive data.

**Comment by xFragger** [comment]
Well, i tried it again, before i mostly used information from a colleague of mine, thats why the enable-cors/cors-enable fault happened. This time i tried anythin by myself, running on newset 0.7 btw, and everything seems fine -.-
so, well, sorry for the interruption
