### ISSUE TITLE
Bring back nbproc-ssl configuration for SSL performance boost

### ISSUE THREAD

**Issue by arep** [jcmoraisjr/haproxy-ingress#529]
Without the possibility to configure nbproc above 1, SSL offloading is not possible. This limits the performance for SSL workloads.
My node is now only using a little above 2 cores (of 8) to do haproxy...and this limits the connections pr second it can handle.

To be able to use haproxy-ingress with high traffic sites using SSL, this is needed.
Is there other possibilities to enable this in current versions? (creating a custom template maybe?)

**Comment by jcmoraisjr** [comment]
Hi, what if you configure [nbthead](https://haproxy-ingress.github.io/docs/configuration/keys/#nbthread) instead? Such functionality need some (ugly) workarounds in the template, and I didn't get the time yet to have a look and propose a good implementation.

**Comment by arep** [comment]
Sure, nbthread works, but not enough. It is only possible to get it to use 2 cores out of 8. Any number above 3 doesn't give additional effect.

**Comment by jcmoraisjr** [comment]
Hi, I can confirm nbthread doesn't scale beyond `4` on our cluster; here haproxy uses at most almost 3 CPUs.

Please give a few more details about this scenario:

- Can you confirm nbproc scale better? Do you have a way to test v0.7 or you used to use it? My concern is that we would be changing a TLS handshake overhead to a connection rate bottleneck - which need to be twice as much due to the inter-process communication.
- Which metrics do you use to know that haproxy doesn't scale to more than 2 CPUs? In other words, how do you know you cannot scale?

**Comment by arep** [comment]
I conducted some test again.
I sent SSL requests with keep-alive off. I was able to get around 25000 req/sec with nbproc=7, nbthread=1
I then switched to nbthread=4.
It seemed I got about the same req/sec, but now the haproxy stats where much more irregular, jumping more up and down between 4-5000 and 30000 req/s.
The CPU utilization seemed to be almost the same for the two workloads.

The reason nbthreads doesn't scale beyond 4 is probably because (at least on my server), that the CPU has 4 physical cores, and hyperthreading doesn't help in this scenario.

Real world traffic will use the ssl_cache, so I think there should be no problems actually. I see around 40% ssl_cache usage on the live servers.
