### ISSUE TITLE
Use two container in one Pod rather than dumb-init

### ISSUE THREAD

**Issue by ailenli** [jcmoraisjr/haproxy-ingress#562]
Hello, all
recently ,I do some research about haproxy-ingress
haproxy-ingress use dumb-init to manage ingress-controller process and haproxy process
such as process management and signal broadcast

I have an idea about change this infrasturce to below:
Two container in One Pod
ingress-controller as a Container,haproxy as other Container , use unix socket for IPC
these two container share data (haproxy.cfg)

here are some Pro
1. convenient for liveness and readiness probe
 container shoule have a liveness,readiness probe,if ingress-controller & haproxy in same container,which present the liveness or readiness? 
In new infrastructure,ingress-controller and haproxy have their own liveness-probe and readiness probe

2. More stable
If controller and haproxy in same container, Once controller has some bugs and crashed,It may be affect haproxy,for example controller cost a lot of memory and up to docker limit
in new infrastruce, each docker has their own resource limit, so they will not affect others
consider that We should make haproxy more reliable, so traffic can be routed

thank you for reading soooo many charactors about this question
Best Regards

**Comment by jcmoraisjr** [comment]
Hi, the current topology comes from a time haproxy didn't have master-worker mode and the controller need eventually to restart the process, which would be a mess to control in another container. Btw I confess I don't know if master-work can help here. This isn't the first time this approach is questioned, I'll definitely have a look.

Regarding the benefits: I'm not that confident this would increase stability since I think the whole pod would restart if one container crashes; liveness and readiness can be controlled by the controller which can also check the haproxy process; and finally you can calc requests and limits to the whole fat container - just remember haproxy need eventually to be restarted and, depending on the frequency, the number of keepalive/websockets of your workload and the timeout-stop configuration you'll have a couple of them in memory.

**Comment by jcmoraisjr** [comment]
An update here, v0.12 has now the ability to deploy a sidecar container with haproxy in master-worker mode. A snapshot tag will be released in a few more days.
