### ISSUE TITLE
Turn off HttpOnly flag for affinity cookie

### ISSUE THREAD

**Issue by maxnowack** [jcmoraisjr/haproxy-ingress#566]
I need to turn off the `httponly` flag in my setup for some reasons.
I've saw that the flag is set [in the template](https://github.com/jcmoraisjr/haproxy-ingress/blob/master/rootfs/etc/haproxy/template/haproxy.tmpl#L435), if the cookie strategy is `insert`.
Switching to another strategy than `insert` isn't an option for me.
For now, I've forked the project and hardcoded the removal of `httponly`.
It would be great if there is an option to disable `httponly` or the ability to finetune the cookie strategy.
I'm willing to create a pull request for such functionality, but I think we should discuss how it could most adequately be implemented.

**Comment by jcmoraisjr** [comment]
Hi, thanks for evaluate haproxy ingress, try a local fix, patch the template, share a feature proposal, start a proposal discussion and the ability to open a PR o/ =)

I'd follow here with another config key, eg `session-cookie-keywords`, with space delimited haproxy keywords which defaults to empty. If declared, this will override the auto-generated keywords used by `session-cookie-strategy`.

It would also be great a regex validating if only valid keywords are being used, something like `^((key1|key2|...) )+$`. There are some config parsing using this approach which can be used as a reference.

Please share your thoughts as well and let me know if I can help in any way.

**Comment by MartinKirchner** [comment]
Hey guys,
I also stumbled upon the additional flags in the `cookie` options. In my case it's about the `indirect` flag.
The application I need to deploy must be able to get the value of the session affinity cookie as it is handed down to another application (please don't argue with me about the system architecture).
That's why I have to use `insert` and get rid of the `indirect` keyword.
The proposed solutionwith `session-cookie-keywords` would just be fine.

Before I learn how to write Go templates I'd love to hear if any of you is working on this.
Thanks a lot in advance.

**Comment by jcmoraisjr** [comment]
First snapshot of v0.11 was just released with this option. Closing. Let me know if you have any problem.
