### ISSUE TITLE
HTTPS host header support

### ISSUE THREAD

**Issue by ausmith** [jcmoraisjr/haproxy-ingress#58]
Technically, host headers should not be supported for HTTPS connections and the SNI headers that have been chosen as the primary way to determine which frontend/backend to use is the correct way to do it in this ingress controller.

HOWEVER! We ended up with a business use case where my team had to enable host header backend selection in the haproxy config template for HTTPS connections. Please let me know if you would like a PR opened against upstream with this solution, I will gladly submit it. Just unsure it belongs (it is gross...).

**Comment by jcmoraisjr** [comment]
So how this should work? Which frontend would match the header? Afaics this
cannot be the tcp frontend listening 443 because the content is still
encrypted.


Em 06/10/2017 11:51, "Aaron Goldsmith" <notifications@github.com> escreveu:

Technically, host headers should not be supported for HTTPS connections and
the SNI headers that have been chosen as the primary way to determine which
frontend/backend to use is the correct way to do it in this ingress
controller.

HOWEVER! We ended up with a business use case where my team had to enable
host header backend selection in the haproxy config template for HTTPS
connections. Please let me know if you would like a PR opened against
upstream with this solution, I will gladly submit it. Just unsure it
belongs (it is gross...).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jcmoraisjr/haproxy-ingress/issues/58>, or mute the
thread

**Comment by ausmith** [comment]
That is correct, the `frontend httpsfront` is unable to actually do the header processing, causing us to wait until the `frontend httpsfront-default-backend` section to select the proper backend. Like I said, it is gross.

https://github.com/ausmith/haproxy-ingress/compare/rewrite_annotations...ausmith:add_host_header_support?expand=1 is a relatively clean diff (though the commit history needs work) of the host header additions that "worked" well enough (builds off my `rewrite_annotations` work or I would have the diff against master here).

**Comment by jcmoraisjr** [comment]
I'm fine with this proposal provided that it's behind a configmap option `use-host-on-https` (or a better name) which defaults to false.

Perhaps you don't need to change the tcp frontend (httpsfront), I think the http headers cannot be read there.

**Comment by ausmith** [comment]
You're likely right that it doesn't need to be in the `httpsfront` block. I will work on removing that + adding a configmap option before opening the PR. Hopefully will get to that this week.

**Comment by jcmoraisjr** [comment]
Nice. Just to let you know I'm finishing a really big refactor on the template and I'd suggest you start a new implementation only after this refactor is pushed to master. This should be there later today or at most tomorrow.

**Comment by ausmith** [comment]
Understood. I think I might have already implemented it with the current code, but will refactor it over those changes you are currently working on.

**Comment by jcmoraisjr** [comment]
Most of the refactor was pushed to master and I'll wait your PR before finishing the changes. Note that now you can proxy to the http/s frontends just like the http frontend does instead of iterating over all locations. This should simplify your changes.

**Comment by ausmith** [comment]
Theoretically https://github.com/jcmoraisjr/haproxy-ingress/compare/master...ausmith:https_host_header_support?expand=1 is the required change, but I have not gotten a chance to test and verify that PR yet and am going on vacation for the next 6 days. I will bring a laptop, not making any promises. Please let me know if opening this PR prior to me doing verification is desired.

**Comment by jcmoraisjr** [comment]
I'd try to proxy to `httpback` backend in order to reuse their already implemented validations - rate limit, white list, body size and so on - just like httpsfront (sni) is doing. Something like this:

```
frontend httpsfront
-> backend httpsback-default-backend
   -> frontend httpsfront-default-backend
      -> backend httpback-{{ $host }}
         -> frontend httpfront-{{ $host }}
```

If following this approach `X-Forwarded-Proto` should probably be added with https on `httpsfront-default-backend` so `httpfront-{{ $host }}` knows how to handle the request.

**Comment by ausmith** [comment]
I will look into this approach, could simplify things nicely. No ETA though, likely sometime next week at the earliest.

**Comment by abh** [comment]
FWIW I've run into needing this, too (grr SparkPost!).

**Comment by ausmith** [comment]
Yesterday I found a bug with the implementation my team is using internally (very similar to the above diff link) where it multiple ingresses configured with the same domain name but different paths can cause unexpected behaviors. When I finally get around to opening my PR for this feature, I plan to have that behavior handled (hopefully...).

**Comment by jcmoraisjr** [comment]
55d994a has a starting implementation. Use this same issue to notify any problem.

**Comment by jcmoraisjr** [comment]
Current snapshot tag has also this implementation. Docs are also updated. Please update this issue with any problem regarding `host` header usage on tls requests. @ausmith let me know if everything is working as expected closing this issue.

**Comment by jcmoraisjr** [comment]
Closing. Just update this issue if you have any problem.
