### ISSUE TITLE
Add a non scoped configuration snippet - eg for cache

### ISSUE THREAD

**Issue by vitobotta** [jcmoraisjr/haproxy-ingress#581]
Hi!

Is it possible to implement microcaching with an ingress? I am looking to cache pages for 5-10 seconds to reduce load on my app. I can do this with nginx but I am not sure of how to do it with haproxy ingress. Thanks!

**Comment by jcmoraisjr** [comment]
Hi, this is currently not possible due to the lack of a way to create a cache section. You can however overwrite the template file, add a hardcoded [cache section](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#10) and configure cache-use/cache-store via [`config-backend`](https://haproxy-ingress.github.io/docs/configuration/keys/#configuration-snippet) config key. Added to the backlog.

**Comment by vitobotta** [comment]
Hi @jcmoraisjr , gotcha. I was hoping I could do this with haproxy out of the box :)

**Comment by jcmoraisjr** [comment]
Hi, reopening so this won't be forgotten.

**Comment by jcmoraisjr** [comment]
Implemented in `v0.13.0-snapshot.1` which was just released and adds a way to create new haproxy sections in the config file, as well as other custom config options. Closing.
