### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ausmith** [jcmoraisjr/haproxy-ingress#62]
I am curious if there are pre-existing plans to add testing to this project? Doing go based unit tests seem like they might be relatively easy to do (though I have limited golang experience myself, so could be very wrong there). System testing on the other hand should exercise the entire project nicely and be possible in `minikube` (unaware if there are services that will provide a full cluster for testing purposes).

I ask as I would like to add some test cases with whatever approach(s) will be used for at least the rewrite-annotation work that I did that has been merged.

**Comment by jcmoraisjr** [comment]
Yep, I have some e2e tests which still need to be prepared, executed and checked manually - because of this they weren't added to the repo yet. Unit tests are a great piece of code that I didn't take the time to start... yet.

Most of the functionalities - like `rewrite-annotation` - are hard to unit test because they come from the ingress core (vendor) straight to the haproxy template. This partially explain my preference to e2e tests. Btw I'll reevaluate on how to evolve them so perhaps I can add my tests to the repo in the near future.

**Comment by jcmoraisjr** [comment]
Since v0.8 we don't use ingress vendor and have also a good test coverage. Most of the new development also uses TDD. This doesn't sound to be an issue anymore, closing.
