### ISSUE TITLE
acme: Adding a domain to a ingress resource should regenerate the certificate

### ISSUE THREAD

**Issue by tim-smart** [jcmoraisjr/haproxy-ingress#664]
**Description of the problem**

Adding a domain to an ingress resource should regenerate the certificate.

I added a domain to an ingress resource, and errors appeared in the logs explaining that the new domain wasn't in the certificate.

**Expected behavior**

Instead, the ingress/acme watcher should just recreate the certificate.

**Environment information**

HAProxy Ingress version: `v0.10`

**Comment by jcmoraisjr** [comment]
Please add also the controller logs.

**Comment by tim-smart** [comment]
```
acme: error signing new certificate: id=9 secret=redirect/redirect-tls domain(s)=redacted,list,of,domains error=acme: authorization error: domain=thenewdomain.com status=invalid
```

This was the error. I have removed the domains from the log entry, but hopefully it makes sense!

As a work-around, I deleted the ingress + tls secret and then re-created the ingress resource.

**Comment by jcmoraisjr** [comment]
I didn't remember the message error from memory but perhaps it was an error between the acme server and your domain during the challenge, so the acme server refused to sign the certificate because of the `thenewdomain.com` that couldn't be validated. Did you see any other acme related message in the controller log? Note that all the controllers (if you have more than one) can receive challenges. The controller does log the challenge request as well. When you remove and recreate the ingress the sign process started again and the problem should have been solved in the mean time?

**Comment by tim-smart** [comment]
Looking back at the logs this is the only related message I found:

```
acme: authorizing: id=9 secret=redirect/redirect-tls domain(s)=list,of,domains,including,thenewdomain.com endpoint=https://acme-v02.api.letsencrypt.org reason='added one or more domains to an existing certificate'
```

Yes, removing and re-creating the ingress resource is a work-around.

**Comment by tim-smart** [comment]
I'll close this for now as I think it was a DNS issue.

I'll try removing and re-adding the domain from the ingress and re-open if there are any issues.

**Comment by jcmoraisjr** [comment]
The sign process is pretty much the same when creating an ingress from zero or editing and adding a new domain, so this doesn't seem to be a workaround, but instead a "before there was an infra issue but now its ok".

In the case of a new problem let the controller itself try again just to see if the problem solves by itself. Please update this issue if you have any other related problem.
