### ISSUE TITLE
Support logs to stdout with Haproxy 2.x

### ISSUE THREAD

**Issue by mbwhelan** [jcmoraisjr/haproxy-ingress#665]
**What are you trying to do**

Collect log output without need of syslog server.

**What HAProxy Ingress should do or how it should behave differently**

Add configuration support to use sysout logging added to Haproxy 2.0.  
https://www.haproxy.com/blog/haproxy-2-0-and-beyond/#cloud-native-threading-logging

**Comment by jcmoraisjr** [comment]
Now v0.12 has the ability to manage haproxy as a sidecar container, doc starts [here](https://haproxy-ingress.github.io/v0.12/docs/configuration/command-line/#master-socket). Let me know if you have any problem. Closing.

**Comment by rikatz** [comment]
Hi @mbwhelan 

I was talking with @jcmoraisjr to understand the problem here, and would like to clarify a little bit.

The logging sink from new HAProxy that allows it writting to stdout is based in filedescriptors, as you can see [here](https://github.com/haproxy/haproxy/blob/0237c4e3f5deb062e8714d02588c86d48fa2703c/src/sink.c#L83)

The main problem here, is that HAProxy writes to its own proc/fd/1, which is not the same that docker uses to print it logs.

Because of Docker's nature, it watches for the stdout of the process with PID 1, (/proc/1/fd/1), that is not the same from HAProxy running inside the container, because actually it's a fork from the ingress-controller binary.

So actually it writes to /proc/30/fd/1 (assuming it's pid is 30), which still makes Docker unaware of the STDOUT.

I've been trying to simulate a scenario where it actually writes to the fd from pid 1, but because of HAProxy code nature, plus restrictions (the haproxy threads run as an unprivileged user) it's not quite possible.

One thing that could be done is to print the logs to stdout and those would be part of the Ingress Controller log, but HAProxy starts as a daemon (flag "daemon") so it sinks its log to /dev/null even if you send to fd 1.

Removing the daemon directive does not seem possible right now, so one thing that could actually be done is to ask for HAProxy devs to log to the fd/1 from the process, even if it's running as a daemon. 

I'm gonna try to deep dive into this and see if something else is possible (one thing is to link /dev/stdout to /proc/1/fd/1 in the startup script, but my concern is, once and if Joao decides to drop the container to run as non-root, is this still happening well?)

Hope you got some answers, and I'm ok also with suggestions :)

**Comment by rikatz** [comment]
OK, so got some 'evolution' here:

Apparently we cannot write to the pid1 FD directly from haproxy.cfg, BUT we can redirect the log to some fd from haproxy and redirect the output from that fd to /proc/1/fd/1

How would this work:

In haproxy.cfg the config of log should be something like

```
log fd@1024 daemon
```

Then starting the haproxy with the command below will redirect everything from fd 1024 to proc/1/fd/1:

```
haproxy -f /etc/haproxy/haproxy.cfg 1024>/proc/1/fd/1
```

This trick might also serve if you want to write your logs to a file, etc.

I wouldn't say it's clean, or even a desired behavior (I don't know if in high load HAProxy wouldn't create a lot of FDs and maybe conflict with this) but, it is what it is

**Comment by rikatz** [comment]
Final thoughts: you can use fd@3 or fd@4 and redirect the 4>/proc/1/fd/1 and this will work.

But IMO I don't think there's a 'beautiful solution' in this case, so probably we need to better discuss if this is a feature for the ingress, or if it's better to stick with a sidecar collector that can also split the logs from the controller, the haproxy process and the requests correctly :)
