### ISSUE TITLE
Confusing log message when configuring auth

### ISSUE THREAD

**Issue by abh** [jcmoraisjr/haproxy-ingress#70]
with this

```
      ingress.kubernetes.io/auth-secret: kibana-auth
      ingress.kubernetes.io/auth-type: basic
```

I'm getting this log message:

    W1113 08:50:16.948004       7 backend_ssl.go:41] error obtaining PEM from secret logging/kibana-auth: no keypair or CA cert could be found in logging/kibana-auth

I checked and kibana-auth is only referenced as an auth-secret.

**Comment by jcmoraisjr** [comment]
I couldn't reproduce this. Please update this issue with version and steps or configs if you can recreate this warning on a small cluster.

**Comment by abh** [comment]
Thank you for looking! I'll see if I can reproduce it in minikube.

**Comment by whereisaaron** [comment]
I just updated nginx-ingress to 0.13.0 and started getting this same type of message in the logs. I realise it is a different controller but may some shared code for loading certs?

```
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: developers-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
```

```
W0421 00:08:04.853701       6 backend_ssl.go:48] error obtaining PEM from secret prometheus/developers-basic-auth: no keypair or CA cert could be found in prometheus/developers-basic-auth
W0421 00:08:04.859483       6 backend_ssl.go:48] error obtaining PEM from secret prometheus/developers-basic-auth: no keypair or CA cert could be found in prometheus/developers-basic-auth
```

**Comment by whereisaaron** [comment]
Thanks @jcmoraisjr, however it's the same error message from about the same line of the same-named file (`backend_ssl.go`) so I'm guessing some common code remains :smile:

And both forks are showing the same bug, of parsing opaque Secrets as if they TLS Secrets referenced in an Ingress. So also a reasonable chance the fix is the same? Possibly some watcher/informer behavior change?

**Comment by jcmoraisjr** [comment]
About 70% of the code is still the same - since nov/17 haproxy-ingress doesn't use k8s/ingress as a dependency; this is what I meant with *isn't shared anymore*.

Which version are you using? I tracked all (or most of) the possible paths to this message and couldn't reproduce it on v0.5 (current canary tag), but due to a misconfiguration on secret reading this seems to be possible on v0.4 (current latest).

**Comment by suquant** [comment]
+1 I have appearance same records in logs

**Comment by jcmoraisjr** [comment]
@suquant please check if you have this same issue with `canary` or `snapshot` tags.

**Comment by suquant** [comment]
@jcmoraisjr  Sorry I was getting this with nginx-ingress 0.14.0

**Comment by esukram** [comment]
I am pretty sure, that this is an issue from the nginx ingress controller and not haproxy related:
kubernetes/ingress-nginx#1709

**Comment by abh** [comment]
FWIW, this was the patch/fix for nginx-ingress for the same issue there:

https://github.com/kubernetes/ingress-nginx/pull/2512/files

**Comment by jcmoraisjr** [comment]
Since v0.8 HAProxy Ingress uses its own ingress parser and solved a couple of synchronization issues. Please file a new issue if you still have any related problem.
