### ISSUE TITLE
port number missing on redirection

### ISSUE THREAD

**Issue by surekhakallam** [jcmoraisjr/haproxy-ingress#727]
hi 
i am trying to onboard a tenant .. we are using haproxy and oauth  on a different namespace and our frontend on the other namespace ... here we are able to access our application for which we have the ingress .. and we also tried to access a random page where we are expecting a 404 error page .. but the url is redirecting to the main application url ... but in this url the port number is missing ... 

say suppose     "https://<fqdn>:<port>/ "      -> is our main application ... its redirecting and giving us the exact page of what we are expecting
but when we use something like      "  https://<fqdn>:<port>/example  " we are expecting a 404 page not found error ... but its redirecting to something like      "   https://<fqdn>/   "  which is not according to what we are expecting ... 
could you please guide us on how to fix this issue

Thanks in advance

**Comment by jcmoraisjr** [comment]
This isn't clear enough but, instead of start a thread here, I'd invite you to post this question on the mailing list, stack overflow or slack. We're on all of them and we're also trying to leave this tracker only to bugs and features. Please paste some configuration snippets like the global config (the configmap content) and the ingress resources used to configure haproxy. Thanks!
