### ISSUE TITLE
Config-backend config map key not working as expected in v0.12.9

### ISSUE THREAD

**Issue by rexhinvorpsi** [jcmoraisjr/haproxy-ingress#854]
**Description of the problem**
Hi we switched our haproxy version from 0.12.3 to 0.12.9 to remidiate the HTTP/2 vulnerability. 
After that the config-backend snippet is not set in the haproxy.cfg even though it is set in the config-map correctly. We traced down to the last working version being 0.12.5.

**Expected behavior**
backend snippets to be set in haproxy.cfg

**Environment information**

HAProxy Ingress version: `v0.12.9`

**Comment by jcmoraisjr** [comment]
Sorry about the annoying regression. I can confirm that backend snippet configuration is broken since #820, planning to tag a new version later this week. Please confirm if only ConfigMap based (global) configuration snippet is broken, as far as I can see, annotation based config snippets are still working.

**Comment by jcmoraisjr** [comment]
Fixed in all supported versions. Closing.
